### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by k-bx** [TomMD/friday-juicypixels#6]
Latest friday-juicypixels on hackage requires base < 4.10, while github has constraint < 4.11, please make a hackage release. Thank you!

**Comment by TomMD** [comment]
Please see https://hackage.haskell.org/package/friday-juicypixels-0.1.2.2

**Comment by TomMD** [comment]
Do you want maintainer access on Hackage?  Push access?

**Comment by k-bx** [comment]
@TomMD I wouldn't mind both, thanks. My hackage username is `k_bx`

**Comment by TomMD** [comment]
Done.

**Comment by k-bx** [comment]
thank you!
